FROM $NODE_IMAGE_NAME as builder

RUN npm run build

FROM nginx:alpine

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/dist /usr/share/nginx/html
COPY --from=builder /usr/src/app/nginx/conf/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /usr/src/app/nginx/conf/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
